In [4]:
## Logistics
import numpy as np
x = np.array([1,2,3,4])
1/(1+np.exp(-x))

array([0.73105858, 0.88079708, 0.95257413, 0.98201379])

In [ ]:
import numpy as np
from random import shuffle

def sigmoid(x):
    h = np.zeros_like(x)
    
    #############################################################################
    # TODO: Implement sigmoid function.                            #         
    #############################################################################
    #############################################################################
    #                     START OF YOUR CODE                  #
    #############################################################################
    h = 1/(1+np.exp(-x))
    
    #############################################################################
    #                     END OF YOUR CODE                   #
    #############################################################################
    return h 

def logistic_regression_loss_naive(W, X, y, reg):
    """
      Logistic regression loss function, naive implementation (with loops)

      Inputs have dimension D, there are C classes, and we operate on minibatches
      of N examples.

      Inputs:
      - W: a numpy array of shape (D, C) containing weights.
      - X: a numpy array of shape (N, D) containing a minibatch of data.
      - y: a numpy array of shape (N,) containing training labels; y[i] = c means
        that X[i] has label c, where c can be either 0 or 1.
      - reg: (float) regularization strength

      Returns a tuple of:
      - loss: (float) the mean value of loss functions over N examples in minibatch.
      - gradient: gradient wrt W, an array of same shape as W
    """
    # Set the loss to a random number
    loss = None
    # Initialize the gradient to zero
    dW = None

    #############################################################################
    # TODO: Compute the softmax loss and its gradient using explicit loops.    #
    # Store the loss in loss and the gradient in dW. If you are not careful    #
    # here, it is easy to run into numeric instability. Don't forget the      #
    # regularization!                                        #
    #############################################################################
    #############################################################################
    #                     START OF YOUR CODE                  #
    #############################################################################
    loss = 100000
    dW = 0
    step = 0.001
    iteration = 5000
    for iter_time in range(iteration):
        m = X.shape[0]
        sigma = sigmoid(X*W)
        loss = -(y*np.log(sigma) + (1-y)*np.log(1-sigma))/m
        dW = X.T*(y-sigma)/m
        W = W - step*dW
    return loss,dW
    
    
    
    
    
    #############################################################################
    #                     END OF YOUR CODE                   #
    #############################################################################

    return loss, dW



def logistic_regression_loss_vectorized(W, X, y, reg):
    """
    Logistic regression loss function, vectorized version.

    Inputs and outputs are the same as softmax_loss_naive.
    """
    # Set the loss to a random number
    loss = None
    # Initialize the gradient to zero
    dW = None

    ############################################################################
    # TODO: Compute the logistic regression loss and its gradient using no    # 
    # explicit loops.                                       #
    # Store the loss in loss and the gradient in dW. If you are not careful   #
    # here, it is easy to run into numeric instability. Don't forget the     #
    # regularization!                                       #
    ############################################################################
    #############################################################################
    #                     START OF YOUR CODE                  #
    #############################################################################
    
    
    
    
    #############################################################################
    #                     END OF YOUR CODE                   #
    #############################################################################

    return loss, dW


In [21]:
def sigmoid(x):
    h = 1/(1+np.exp(-x))
    return h 

def logistic_regression_loss_naive(W, X, y):
    loss = 100000
    dW = 0
    step = 0.001
    iteration = 5000
    for iter_time in range(iteration):
        m = X.shape[0]
        sigma = sigmoid(X*W)
        #loss = -(np.dot(y,np.log(sigma)) + np.dot((1-y),np.log(1-sigma)))/m
        dW = -X.T*(y-sigma)/m
        W = W - step*dW
    return dW
W = np.matrix([[2,3],[5,6],[7,8]])
X = np.random.rand(4,3)
y = np.matrix([[1,0],[0,1],[1,0],[0,1]])
W_1 = logistic_regression_loss_naive(W,X,y)
X*W_1

matrix([[0.54118485, 0.41067798],
        [0.61109919, 0.47035551],
        [0.19317701, 0.15881461],
        [0.37073191, 0.29019106]])

In [23]:
np.array([0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1]).reshape([-1, 1])

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [ ]:
import numpy as np
from random import shuffle

def softmax_loss_naive(W, X, y, reg):
    """
      Softmax loss function, naive implementation (with loops)

      Inputs have dimension D, there are C classes, and we operate on minibatches
      of N examples.

      Inputs:
      - W: a numpy array of shape (D, C) containing weights.
      - X: a numpy array of shape (N, D) containing a minibatch of data.
      - y: a numpy array of shape (N,) containing training labels; y[i] = c means
        that X[i] has label c, where 0 <= c < C.
      - reg: (float) regularization strength

      Returns a tuple of:
      - loss: (float) the mean value of loss functions over N examples in minibatch.
      - gradient: gradient wrt W, an array of same shape as W
    """
    # Initialize the loss and gradient to zero.
    loss = 0.0
    dW = np.zeros_like(W)

    #############################################################################
    # TODO: Compute the softmax loss and its gradient using explicit loops.    #
    # Store the loss in loss and the gradient in dW. If you are not careful    #
    # here, it is easy to run into numeric instability. Don't forget the      #
    # regularization!                                        #
    #############################################################################
    #############################################################################
    #                     START OF YOUR CODE                  #
    #############################################################################
    

    
    #############################################################################
    #                     END OF YOUR CODE                   #
    #############################################################################

    return loss, dW


def softmax_loss_vectorized(W, X, y, reg):
    """
    Softmax loss function, vectorized version.

    Inputs and outputs are the same as softmax_loss_naive.
    """
    # Initialize the loss and gradient to zero.
    loss = 0.0
    dW = np.zeros_like(W)

    #############################################################################
    # TODO: Compute the softmax loss and its gradient using no explicit loops.  #
    # Store the loss in loss and the gradient in dW. If you are not careful    #
    # here, it is easy to run into numeric instability. Don't forget the      #
    # regularization!                                        #
    #############################################################################
    #############################################################################
    #                     START OF YOUR CODE                  #
    #############################################################################
    ##define gradient descent model
    K = 10
    def gradient_descent(W,X,y,class_num,iteration,step):
        for iter_ in range(iteration):
            value = np.exp(W*X)
            rowsum = value.sum(axis=1)
            rowsum = rowsum.repeat(class_num,axis=1)
            loss = -y*np.log(value/rowsum)
            dW = (y-value)X.shape[0]
            
        

    
    #############################################################################
    #                     END OF YOUR CODE                   #
    #############################################################################

    return loss, dW